In [14]:
import netket as nk
from netket.operator.spin import sigmax, sigmay, sigmaz
import numpy as np
import json
from math import pi


In [23]:

L = 10
g = nk.graph.Chain(length=L, pbc=False)
N = g.n_nodes
hi = nk.hilbert.Spin(s=1, N=N)

H = 0
#print(g.edges())
print(g.adjacency_list())


#print(sigmax(hi,0).to_dense())
#print(sigmay(hi,0).to_dense())
#print(sigmaz(hi,0).to_dense())

for i, j in g.edges():
    #operators, weights = ['XX','YY','ZZ'], [1,1,1]
    #dotpr = nk.operator.PauliStrings(operators, weights)
    dotpr = sigmaz(hi, i)*sigmaz(hi, j) + sigmax(hi, i)*sigmax(hi, j) + sigmay(hi, i)*sigmay(hi, j)
    H += 1/2 * dotpr + 1/6 * dotpr*dotpr + 1/3

[[1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7], [6, 8], [7, 9], [8]]


In [11]:
sx = np.array([[0, 1],[1, 0]], complex)
sy = np.array([[0, -j],[j, 0]], complex)
sz = np.array([[1, 0],[0, -1]], complex)

SX = np.kron(sx, sx)
SY = np.kron(sy, sy)
SZ = np.kron(sz, sz)

np.matmul(SX,SX) + np.matmul(SY,SY) + np.matmul(SZ,SZ)

array([[4098.+0.j,    0.+0.j,    0.+0.j,    0.+0.j],
       [   0.+0.j, 4098.+0.j,    0.+0.j,    0.+0.j],
       [   0.+0.j,    0.+0.j, 4098.+0.j,    0.+0.j],
       [   0.+0.j,    0.+0.j,    0.+0.j, 4098.+0.j]])

In [39]:
#Couplings J1 and J2
J = [1, 0.2]
L = 14

# Define custom graph
edge_colors = []
for i in range(0, L, 2):
    edge_colors.append([i, (i+1)%L, 1])
    #edge_colors.append([i, (i+2)%L, 2])
print(edge_colors)

# Define the netket graph object
g = nk.graph.Graph(edges=edge_colors)

#Sigma^z*Sigma^z interactions
sigmaz = [[1, 0], [0, -1]]
mszsz = (np.kron(sigmaz, sigmaz))

#Exchange interactions
exchange = np.asarray([[0, 0, 0, 0], [0, 0, 2, 0], [0, 2, 0, 0], [0, 0, 0, 0]])

print((J[0] * mszsz))
print((J[0] * mszsz).tolist())

bond_operator = [
    (J[0] * mszsz).tolist(),
    (J[1] * mszsz).tolist(),
    (-J[0] * exchange).tolist(),  
    (J[1] * exchange).tolist(),
]

bond_color = [1, 2, 1, 2]

print(np.shape(bond_operator))
print(bond_operator)

[[0, 1, 1], [2, 3, 1], [4, 5, 1], [6, 7, 1], [8, 9, 1], [10, 11, 1], [12, 13, 1]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]]
(4, 4, 4)
[[[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]], [[0.2, 0.0, 0.0, 0.0], [0.0, -0.2, 0.0, 0.0], [0.0, 0.0, -0.2, 0.0], [0.0, 0.0, 0.0, 0.2]], [[0, 0, 0, 0], [0, 0, -2, 0], [0, -2, 0, 0], [0, 0, 0, 0]], [[0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.4, 0.0], [0.0, 0.4, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]]


In [36]:
Splus = np.sqrt(2)*np.array([[0, 0, 1, 0],[0, 0, 0, 1],[0, 0, 0, 0],[0, 0, 0, 0]], complex)
Sminus = np.sqrt(2)*np.array([[0, 0, 1, 0],[0, 0, 0, 1],[0, 0, 0, 0],[0, 0, 0, 0]], complex).T

print(Splus)
print(Sminus)
print(np.real(np.matmul(Splus, Sminus)))


[[0.        +0.j 0.        +0.j 1.41421356+0.j 0.        +0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j 1.41421356+0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]]
[[0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]
 [0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]
 [1.41421356+0.j 0.        +0.j 0.        +0.j 0.        +0.j]
 [0.        +0.j 1.41421356+0.j 0.        +0.j 0.        +0.j]]
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
L = 10
#g = nk.graph.Chain(length=L, pbc=True)

edge_colors = []
for i in range(0, L, 2):
    edge_colors.append([i, (i+1)%L, 1])
    #edge_colors.append([i, (i+2)%L, 2])

# Define the netket graph object
g = nk.graph.Graph(edges=edge_colors)

N = g.n_nodes
hi = nk.hilbert.Spin(s=1/2, N=N)

# Should we use full spin vectors instead of just sigmaz?

sx = [[0, 1], [1, 0]]
sy = [[0, -1j], [1j, 0]]
sz = [[1, 0], [0, -1]]
mszsx = np.kron(sx, sx)
mszsy = np.kron(sy, sy)
mszsz = np.kron(sz, sz)
print(mszsx)
H0 = np.eye(4)*1/3
H1 = (mszsx**2 + mszsy**2 + mszsz**2)*1/2
H2 = H1**2*1/6

siteops = []
bondops = [H0+H1+H2]
bondcols = [1]
nk.operator.GraphOperator(hilbert=hi, graph=g, site_ops=siteops, bond_ops=bondops, bond_ops_colors=bondcols)

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


ValueError: The matrix of the sub-operator acting on sites (0, 1) must have shape (9, 9), but it has shape (4, 4).